// Generated by CoffeeScript 1.3.3

/*
This program is distributed under the terms of the MIT license.
Copyright 2012 (c) Markus Kohlhase <mail@markus-kohlhase.de>
*/


/*
This is coffee-script fork of
https://github.com/astro/node-xmpp/blob/master/lib/xmpp/jid.js
*/


(function() {
  var JID, toUnicode;

  toUnicode = (typeof punycode !== "undefined" && punycode !== null ? punycode.toUnicode : void 0) || function(a) {
    return a;
  };

  JID = (function() {

    function JID(a, b, c) {
      if (a && !(b != null) && !(c != null)) {
        this.parseJID(a);
      } else if (b != null) {
        this.setUser(a);
        this.setDomain(b);
        this.resource = c;
      } else {
        throw new Error('Argument error');
      }
    }

    JID.prototype.user = null;

    JID.prototype.resource = null;

    JID.prototype.domain = null;

    JID.prototype.parseJID = function(s) {
      if (s.indexOf('@') >= 0) {
        this.setUser(s.substr(0, s.indexOf('@')));
        s = s.substr(s.indexOf('@') + 1);
      }
      if (s.indexOf('/') >= 0) {
        this.resource = s.substr(s.indexOf('/') + 1);
        s = s.substr(0, s.indexOf('/'));
      }
      return this.setDomain(s);
    };

    JID.prototype.toString = function() {
      var s;
      s = this.domain;
      if (this.user) {
        s = this.user + '@' + s;
      }
      if (this.resource) {
        s += '/' + this.resource;
      }
      return s;
    };

    JID.prototype.bare = function() {
      if (this.resource) {
        return new JID(this.user, this.domain, null);
      } else {
        return this;
      }
    };

    JID.prototype.equals = function(other) {
      return this.user === other.user && this.domain === other.domain && this.resource === other.resource;
    };

    JID.prototype.setUser = function(user) {
      return this.user = user && user.toLowerCase();
    };

    JID.prototype.setDomain = function(domain) {
      return this.domain = domain && (domain.split(".").map(toUnicode).join(".")).toLowerCase();
    };

    return JID;

  })();

  window.JID = JID;

}).call(this);
